CREATE DATABASE IF NOT EXISTS COLLEGE_DB;
CREATE SCHEMA IF NOT EXISTS COLLEGE_DB.ACADEMICS;

CREATE ROLE IF NOT EXISTS COLLEGE_ADMIN;
CREATE ROLE IF NOT EXISTS FACULTY_ROLE;

-- Database-level control
GRANT ALL PRIVILEGES
ON DATABASE COLLEGE_DB
TO ROLE COLLEGE_ADMIN;

-- Schema-level control
GRANT ALL PRIVILEGES
ON ALL SCHEMAS IN DATABASE COLLEGE_DB
TO ROLE COLLEGE_ADMIN;

-- Future schemas too (important!)
GRANT ALL PRIVILEGES
ON FUTURE SCHEMAS IN DATABASE COLLEGE_DB
TO ROLE COLLEGE_ADMIN;

-- Allow schema visibility
GRANT USAGE
ON DATABASE COLLEGE_DB
TO ROLE FACULTY_ROLE;


GRANT USAGE
ON SCHEMA COLLEGE_DB.ACADEMICS
TO ROLE FACULTY_ROLE;

-- Read-only access to existing tables
GRANT SELECT
ON ALL TABLES IN SCHEMA COLLEGE_DB.ACADEMICS
TO ROLE FACULTY_ROLE;

-- Read-only access to future tables
GRANT SELECT
ON FUTURE TABLES IN SCHEMA COLLEGE_DB.ACADEMICS
TO ROLE FACULTY_ROLE;   


CREATE USER IF NOT EXISTS admin_user
PASSWORD = 'Admin@123'
DEFAULT_ROLE = COLLEGE_ADMIN
MUST_CHANGE_PASSWORD = TRUE;


CREATE USER IF NOT EXISTS faculty_user
PASSWORD = 'Faculty@123'
DEFAULT_ROLE = FACULTY_ROLE
MUST_CHANGE_PASSWORD = TRUE;


GRANT ROLE COLLEGE_ADMIN TO USER admin_user;
GRANT ROLE FACULTY_ROLE TO USER faculty_user;


GRANT USAGE
ON WAREHOUSE MY_HCL_TRAINNING
TO ROLE COLLEGE_ADMIN;

GRANT USAGE
ON WAREHOUSE MY_HCL_TRAINNING
TO ROLE FACULTY_ROLE;

GRANT ROLE FACULTY_ROLE TO ROLE COLLEGE_ADMIN;


--creation of table  will be done on admin panel by admin_user

